---
run:
    platform: miseq
    batch: 20220314
    stage: raw
    extension: 'fastq.gz'
    gzip: True
logging: DEBUG
project_path: /data/wellerca/projects/pseudodiploidy/
debug_args:
    - 'src/analyze-sim-reads.py'
    - 'data/input/100-tiny.assembled.fastq'
    - 'data/processed/sample8'
match_length: 35
buffer_length: 0
mismatch_tolerance: 3
amplicons:
    spo13:
        upstream: "TATGCCATTCCCATCCAACGGCCGGAGTTGCTTTATCCGAATGTTAACGTATACGATTCGCCATTGTTTAAGAAAACAAGACTGCCCCATCAGACCAAAAGTCTAGATAAAGAAAAAAATTACCAATATCTTCCAATATATCCGGTCTCGATTTCTAATAACGGAGATTTTGTTGGCCAAGAGACA"
        downstream: "AAGGGCAGCACCAAAGTTAAGTAAAAAGAGACTTTCAAATACATTGGATGTTAATTGTTCCGATTATGAGTCTAGTGGAC"
        wt: "CC"
        edit: "TG"
    his2:
        PAM:    'AGG'
        upstream: "GGATCATTAACGAATTGCGAAATGGGTAATCTCTTTACAGTTAACAGATTCTCTGGTGATTGGCTT"
        downstream: "CTCAAGGTAGCAAATATACTCTAATTGTAGCACGTCTACTATGTATTTCTTTACCTTGTCATAGCACACACCCACTTGCGCCACGCCGTGTGCGTCATCACTTAGAACAAATCTGGATCCACAGTGCTTCTTGACCAGATTACATAAGGTTTTGCTGGGGTACGGCTCCTCGAGGCGCTTTCTTAATGCGGACGTATTGATTTCAATTGCGC"
        wt: "TC"
        edit: "CA"
    can1:
        upstream: "TACATGTAACCATTGGCCGCACCAAATGCTGGAGAAAGGAATCTTTGTGAGAAAACTGTGAAAGAGGATGTAACAGGGATGAATGTAGCCATTTCACCCAAGGACTGCGTGACAGAATATGCCAAAGAACCCATAAATAAATATGATATAAGAGC"
        downstream: "CACTGGGCCGGCGTTGGTCAGAGGTGTGGATAAACCAATGAAAAGACCTGTACCAATAGTACCACCAAGGGCAATCATACCAATATGTCTTTGCTTAAGCTCTCTCTTCACTTCAGCGTTCTGTACTTCTCCTTCATCTTCATCACCTATGCCATCC"
        wt: "GCC"
        edit: "TTA"


