---
run:
    platform: miseq
    batch: 20220314
    stage: raw
    extension: 'fastq.gz'
    gzip: True
logging: DEBUG
project_path: /data/wellerca/projects/pseudodiploidy/
debug_args:
    - 'src/analyze_sim_reads.py'
    - 'data/processed/100-tiny.assembled.fastq.counts'
pad_left: 10
pad_right: 10
pct_mismatch_tolerances:
    - 0.00
    - 0.01
    - 0.02
dist_around_edit: 20
amplicons:
    spo13:
        upstream: "TATGCCATTCCCATCCAACGGCCGGAGTTGCTTTATCCGAATGTTAACGTATACGATTCGCCATTGTTTAAGAAAACAAGACTGCCCCATCAGACCAAAAGTCTAGATAAAGAAAAAAATTACCAATATCTTCCAATATATCCGGTCTCGATTTCTAATAACGGAGATTTTGTTGGCCAAGAGACA"
        downstream: "AAGGGCAGCACCAAAGTTAAGTAAAAAGAGACTTTCAAATACATTGGATGTTAATTGTTCCGATTATGAGTCTAGTGGAC"
        cut_site: 192
        wt: "CC"
        edit: "TG"
    his2:
        upstream: "GGATCATTAACGAATTGCGAAATGGGTAATCTCTTTACAGTTAACAGATTCTCTGGTGATTGGCTT"
        downstream: "CTCAAGGTAGCAAATATACTCTAATTGTAGCACGTCTACTATGTATTTCTTTACCTTGTCATAGCACACACCCACTTGCGCCACGCCGTGTGCGTCATCACTTAGAACAAATCTGGATCCACAGTGCTTCTTGACCAGATTACATAAGGTTTTGCTGGGGTACGGCTCCTCGAGGCGCTTTCTTAATGCGGACGTATTGATTTCAATTGCGC"
        cut_site: 73
        wt: "TC"
        edit: "CA"
    can1:
        upstream: "TACATGTAACCATTGGCCGCACCAAATGCTGGAGAAAGGAATCTTTGTGAGAAAACTGTGAAAGAGGATGTAACAGGGATGAATGTAGCCATTTCACCCAAGGACTGCGTGACAGAATATGCCAAAGAACCCATAAATAAATATGATATAAGAGC"
        downstream: "CACTGGGCCGGCGTTGGTCAGAGGTGTGGATAAACCAATGAAAAGACCTGTACCAATAGTACCACCAAGGGCAATCATACCAATATGTCTTTGCTTAAGCTCTCTCTTCACTTCAGCGTTCTGTACTTCTCCTTCATCTTCATCACCTATGCCATCC"
        cut_site: 162
        wt: "GCC"
        edit: "TTA"


